### ISSUE TITLE
Pat table with Section length > 176 bytes 

### ISSUE THREAD

**Issue by deimspb** [Cinegy/TsDecoder#23]
Hi! Try to parse ts file or udp stream with Pat  section legth more then 176 bytes ( more then 44 services) with an error. Can you add HasAllBytes check in ProgramAssociationTableFactory?
59 services transport stream (36E DVB-S2) ~ 500 mb https://drive.google.com/file/d/1KR2RELPcF3ohW7PFCbMw-ZFmR7MuHJPK/view?usp=sharing

**Comment by lewk2** [comment]
Sorry, took too long to get to this, and the link is dead. If you can re-attach a link, I'll take a look (nothing on my UK satellites gets close to this many services, just tried to find some).

**Comment by lewk2** [comment]
Closing as old (and a lot of refactoring has now been committed since)
