### ISSUE TITLE
SDT-other BAT tables support

### ISSUE THREAD

**Issue by deimspb** [Cinegy/TsDecoder#24]
Not supported extracting info from SDT-other table(0x46) and BAT tables with table id 0x4A.

**Comment by deimspb** [comment]
Please, add support of this tables in your code. thanks!

**Comment by lewk2** [comment]
SDT other tables are added now, BAT - not (I have no use for BAT - if you really care, open a new issue and please attach a short sample link and I will see if I can do it).

Since we shall split the issue of BAT is really still needed, closing this issue.
