### ISSUE TITLE
Service name in Cyrillic.

### ISSUE THREAD

**Issue by deimspb** [Cinegy/TsDecoder#7]
System.ArgumentException: "'ISO-8859-5' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method."

MPTS transport stream consist of 25 services.

**Comment by lewk2** [comment]
Hi - can you please provide a small TS sample showing the issue? If you want, please fork and add failing sample into '\TestStreams' folder used by unit tests and issue pull request. Try to limit TS sample to 10MB

**Comment by deimspb** [comment]
Hi! ts sample here https://drive.google.com/file/d/0B_0EFotWeTYWZmI0VWkzTm1acm8/view?usp=sharing 30 sec MPTS from 36E DVB-S2.

**Comment by lewk2** [comment]
Fixed - it was a stupid bug hanging over from conversion to NET Standard (earlier NET Standard did not support these modes, but at v1.3 it does - so fix was one line)
